let constants = {
  ARRAY: 'Array',
  ARRAY_BUFFER: 'ArrayBuffer',
  ARGS: 'Arguments',
  DATA_VIEW: 'DataView',
  DATE: 'Date',
  FUNCTION: 'function',
  FLOAT32ARRAY: 'Float32Array',
  FLOAT64ARRAY: 'Float64Array',
  INT8ARRAY: 'Int8Array',
  INT16ARRAY: 'Int16Array',
  INT32ARRAY: 'Int32Array',
  MAP: 'Map',
  NULL: 'null',
  NUMBER: 'number',
  OBJECT: 'Object',
  PROMISE: 'Promise',
  REGEX: 'RegExp',
  SET: 'Set',
  STRING: 'string',
  SYMBOL: 'symbol',
  UINT8ARRAY: 'Uint8Array',
  UINT8CLAMPEDARRAY: 'Uint8ClampedArray',
  UINT16ARRAY: 'Uint16Array',
  UINT32ARRAY: 'Uint32Array',
  UNDEFINED: 'undefined',
  WEAK_MAP: 'WeakMap',
  WEAK_SET: 'WeakSet'
}

export = constants
