interface Constants {
  ARRAY: string,
  ARRAY_BUFFER: string,
  ARGS: string,
  BOOLEAN: string,
  DATA_VIEW: string,
  DATE: string,
  FUNCTION: string,
  FLOAT32ARRAY: string,
  FLOAT64ARRAY: string,
  INT8ARRAY: string,
  INT16ARRAY: string,
  INT32ARRAY: string,
  MAP: string,
  NULL: string,
  NUMBER: string,
  OBJECT: string,
  PROMISE: string,
  REGEX: string,
  SET: string,
  STRING: string,
  SYMBOL: string,
  UINT8ARRAY: string,
  UINT8CLAMPEDARRAY: string,
  UINT16ARRAY: string,
  UINT32ARRAY: string,
  UNDEFINED: string,
  WEAK_MAP: string,
  WEAK_SET: string
}

const Constants: Constants = {
  ARRAY: 'Array',
  ARRAY_BUFFER: 'ArrayBuffer',
  ARGS: 'Arguments',
  BOOLEAN: 'boolean',
  DATA_VIEW: 'DataView',
  DATE: 'Date',
  FUNCTION: 'function',
  FLOAT32ARRAY: 'Float32Array',
  FLOAT64ARRAY: 'Float64Array',
  INT8ARRAY: 'Int8Array',
  INT16ARRAY: 'Int16Array',
  INT32ARRAY: 'Int32Array',
  MAP: 'Map',
  NULL: 'null',
  NUMBER: 'number',
  OBJECT: 'Object',
  PROMISE: 'Promise',
  REGEX: 'RegExp',
  SET: 'Set',
  STRING: 'string',
  SYMBOL: 'symbol',
  UINT8ARRAY: 'Uint8Array',
  UINT8CLAMPEDARRAY: 'Uint8ClampedArray',
  UINT16ARRAY: 'Uint16Array',
  UINT32ARRAY: 'Uint32Array',
  UNDEFINED: 'undefined',
  WEAK_MAP: 'WeakMap',
  WEAK_SET: 'WeakSet'
}

export default Constants
